server:
  port: 8780
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true
        mappedfile: false
    session:
      timeout: 14400  # 4hr 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    max-http-form-post-size: -1 # the maximum size of the whole post request
    max-swallow-size: -1        # the maximum size of a request body
    ajp:
      protocol: AJP/1.3
      port: 8709
      enabled: true
mybatis:
  config-location: classpath:configs/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*.xml 
  
#local setting
---
spring:
  config:
    activate:
      on-profile: "local"
  
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  groovy: 
    template: 
      cache: false
  mustache:
    cache: false
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@//10.64.2.114:1531/RNDPLMDEV
    username: plm
    password: spam!8
    connection-timeout: 20000
    maximum-pool-size: 75
    connection-test-query: SELECT 1 FROM DUAL
    minimum-idle: 10
    pool-name: pool-farin-vue
  transaction:
    default-timeout: 10
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  messages: 
    use-code-as-default-message: true
  servlet:  
    multipart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

fvue:
  maxResultRows: 1000

#dev setting
---
spring:
  config:
    activate:
      on-profile: "dev"
  
  thymeleaf:
    cache: false
  freemarker:
    cache: false
  groovy: 
    template: 
      cache: false
  mustache:
    cache: false
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(9LL6glJDZ6O79c3I/fy8+4NipKMHCkXg1hXgJUYyg/HFfKmpoy9sVC/qA8yML3J4TZNYedTNqlQ=)
    username: ENC(eNVPCH62Y9nZfdOzgcPgMA==)
    password: ENC(GdLvBEaMjLe1U+4dgyBgig==)
    connection-timeout: 20000
    maximum-pool-size: 75